---
build_from:
  aarch64: homeassistant/aarch64-base:latest
  amd64: homeassistant/amd64-base:latest
  armhf: homeassistant/armhf-base:latest
  armv7: homeassistant/armv7-base:latest
  i386: homeassistant/i386-base:latest
labels:
  io.hass.name: "Simply Print Bambu Lab Client"
  io.hass.description: "A Home Assistant addon for the Simply Print Bambu Lab client"
  io.hass.type: "addon"
  io.hass.version: "1.0.0" 