# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Simply Print Bambu Lab Client
# renovate: image="simplyprint/simplyprint-bambu-lab"
version: "1.0.0"
slug: simply-print-bambu
description: A Home Assistant addon for the Simply Print Bambu Lab client - connects your Bambu Lab printer to Simply Print cloud service
url: "https://github.com/yeradon/homeassistant-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - name: data:rw
    path: /root/.config/SimplyPrint
image: "ghcr.io/yeradon/homeassistant-addons/simply-print-bambu-{arch}"
ingress: true
ingress_port: 8000
panel_icon: "mdi:printer-3d"
startup: application
