# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Octoeverywhere Bambu Connect
# renovate: image=octoeverywhere/octoeverywhere
version: "3.6.8"
slug: octoeverywhere
description: A addon to host Octoeverywhere bambulab middleware on your homeassistant os device
url: "https://github.com/yeradon/homeassistant-addons"
init: false
legacy: true
map:
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  CONNECTION_MODE: "local"
schema:
  BAMBU_CLOUD_ACCOUNT_EMAIL: email?
  BAMBU_CLOUD_ACCOUNT_PASSWORD: password?
  CONNECTION_MODE: list(cloud|local)
  SERIAL_NUMBER: str
  ACCESS_CODE: str
  PRINTER_IP: str
image: "octoeverywhere/octoeverywhere"


