name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'simply-print-bambu-client/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'simply-print-bambu-client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker run \
            --rm \
            --privileged \
            -v ${{ github.workspace }}:/data \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            homeassistant/amd64-builder \
            -t /data/simply-print-bambu-client \
            --all \
            -i ${{ github.repository }}/simply-print-bambu-{arch} \
            -d ghcr.io 